version: "3"

services:
  spring:
    image: parksangcheon/spring:latest
    container_name: spring-container
    environment:
      - TZ=${TZ}
      - SPRING_MYSQL_HOST=mysql-container
      - SPRING_REDIS_HOST=redis-container
    volumes:
      - /home/ubuntu/images:/home/ubuntu/images
    ports:
      - "${SPRING_BINDING_PORT}:8081"
    restart: always
    networks:
      - app-network

  react-nginx:
    build:
      context: ..
      dockerfile: ./docker/react-nginx/Dockerfile
    image: react-nginx-custom:latest
    container_name: react-nginx-container
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true

